name: tndwolf_utils
description: A collection of personal utilities.
version: 0.0.1
#author: Luca Carbone <tndwolf@gmail.com>
#homepage: https://www.tndwolf.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0'
